import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const neue = localFont({
  src: [
    {
      path: "./fonts/PPNeueMontreal-Thin.otf",
      weight: "100 300"
    },
    {
      path: "./fonts/PPNeueMontreal-Book.otf",
      weight: "400"
    },
    {
      path: "./fonts/PPNeueMontreal-Medium.otf",
      weight: "500 600"
    },
    {
      path: "./fonts/PPNeueMontreal-Bold.otf",
      weight: "700 900"
    },
  ],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${neue.className} antialiased tracking-wide`}
      >
        {children}
      </body>
    </html>
  );
}
